#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

echo $(pwd)
ls lnInclude
conan install . -s compiler=gcc -s compiler.libcxx=libstdc++11 --build
ls lnInclude
wmake libso
ls lnInclude